"""add profile page i.e bio and profile_pic_path

Revision ID: 00314b423aa8
Revises: ed6981f9faef
Create Date: 2019-09-12 16:33:55.629780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00314b423aa8'
down_revision = 'ed6981f9faef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
